<?php
    $product_shuffle = $product->getData();
?>


        <!-- All Blogs -->
        <section id="all-blogs">
            <div class="container py-5">
                <h4 class="font-rubik font-size-20">All Blogs</h4>
                <hr>
                <div class="blog1 row">
                    <div class="col-12 py-4">
                        <p class="font-rale font-size-20 text-dark font-weight-bold">OnePlus 8 Series to Go on Sale in India Starting May 29: Officialy Announced</p>
                        <img src="./assets/blog/OnePlus8Series_Sale-date.png" alt="blog1">
                    </div>
                    <div class="col-12 py-2">
                        <p class="font-baloo font-size-16">OnePlus has now finally announced that its flagship OnePlus 8 series will go on the first sale in India starting from May 29. OnePlus revealed the Indian pricing for the OnePlus 8 series but due to COVID-19 pandemic, the sale could not be commenced in India. However, the company has now announced through its Red Cable Club community program that the OnePlus 8 and OnePlus 8 Pro will go on sale on May 29. Amazon has already listed the two phones for pre-bookings. This is good news for the OnePlus fans who were waiting for OnePlus 8 Series. The wait is about to end.</p>
                        <p class="font-baloo font-size-16">The company has made announcement on OnePlus Red Cable Club members section, the compay said OnePlus 8 and the OnePlus 8 Pro will go on sale in India starting May 29 across all channels. Moreover, the company has revealed that it will be hosting a special early access sale on May 18 at 2pm, as a part of which, the OnePlus 8 5G will be made available in limited quantity.</p>
                        <p class="font-baloo font-size-16">The OnePlus 8 base variant with 6GB RAM and 128GB storage is priced at Rs 41,999. The base OnePlus 8 version is exclusive to Amazon. The OnePlus 8 with 8GB RAM, 128GB storage variant is priced at Rs. 44,999 and the top variant of the OnePlus 8 with 12GB RAM and 256GB storage will cost you at Rs 49,999. The OnePlus 8 Pro is priced at Rs 54,999 for the 8GB RAM with 128GB storage variant is priced at Rs 54,999 and the 12GB RAM with 256GB storage variant is priced at Rs 59,999. OnePlus 8 comes in three colors like Onyx Black, Glacial Green and Interstellar Glow. OnePlus 8 Pro color variants are Onyx Black, Glacial Green and Ultramine Blue.</p>
                        <p class="font-baloo font-size-16">OnePlus shared in the Red Cable Club’s discover section, that the limited edition Pop-Up Bundle for the OnePlus 8 and OnePlus 8 Pro will cost Rs. 1,000 more than the retail price of the phones and will include the Bullets Wireless Z (Black) earphones, a Cyan bumper case, and Karbon bumper case. The Pop-Up Bundle will be up for an exclusive sale for Red Cable Club members on May 28. The Pop-Up bundle for the OnePlus 8 (Onyx Black, Glacial Green) costs Rs. 45,999 while the Pop-Up bundle for the OnePlus 8 Pro (Onyx Black, Glacial Green) costs Rs. 60,999.</p>
                        <p class="font-baloo font-size-16">Launch offers include Rs 3,000 instant discount on the 8 Pro and Rs 2,000 instant discount on the 8 on purchase via SBI credit cards, up to 12 months no-cost EMI on OnePlus.in and Amazon.in if you purchase using popular bank debit and credit cards, or across all retail channels with SBI credit cards. OnePlus will also offer an opportunity for buyers to purchase the phone at one-third of the value, while paying the remaining amount in low-cost EMIs for 12 months. OnePlus has partnered with Bajaj Finance for this scheme. Finally, Red Cable Club members get 10% off the screen protection plan.</p>
                    </div>
                </div>
                <div class="blog2 row">
                    <div class="col-12 py-4">
                        <p class="font-rale font-size-20 text-dark font-weight-bold">Apple iPhone SE 2020 to go on sale from May 20 in India</p>
                        <img src="./assets/blog/iphonese2020.png" alt="blog2">
                    </div>
                    <div class="col-12 py-2">
                        <p class="font-baloo font-size-16">Apple had launched its iPhone SE 2020 last month with a starting price of Rs. 42,500 in India. But there was no word on the availability of the device in India. Now a Flipkart listing has confirmed that Apple iPhone SE 2020 sale will start in India from May 20 via Flipkart at 12PM. Notably, HDFC Bank recently announced a instant discount offer that brings the effective price of the iPhone SE (2020) 64GB variant down to Rs. 38,900 and this offer will be available via Flipkart. The new Apple phone is powered by the A13 Bionic SoC and packs a single 12-megapixel camera at the back. A few days back Apple announced an offer for HDFC Bank cards by offering Rs 3,600 cashback making the effective price Rs 38,900 of the iPhone SE 2020. Apple supplier Redington has also already confirmed that the phone will be available in 3500+ retail locations across India. After the HDFC bank offer, consumers will be able to purchase the iPhone SE 2020 64GB model at Rs 38,900, 128GB storage model at Rs 44,200, and 256GB storage at Rs 54,700.  The iPhone SE (2020) is offered Black, White, and PRODUCT (RED) color options.</p>
                        <p class="font-baloo font-size-16">The iPhone SE (2020) features a 4.7-inch Retina HD (750×1334 pixels) IPS LCD display with True Tone tech and Haptic Touch support. It is powered by the Apple A13 Bionic chip. The iPhone SE (2020) runs on iOS 13. The phone has a single 12-megapixel camera sensor (f/1.8 aperture + OIS) at the back along with a LED True Tone flash. Camera features include 4K video at 60fps, Portrait mode, and Smart HDR. For selfies and video chat, there is a 7-megapixel camera at the front, with f/2.2 aperture.</p>
                        <p class="font-baloo font-size-16">iPhone SE (2020) connectivity include 4G VoLTE, Wi-Fi 802.11ax, NFC, Bluetooth v5.0, GPS/ A-GPS, and a Lightning port. It lacks a 3.5mm audio port, but offers IP67 water and dust resistance, and comes with Touch ID support. The phone measures 138.4×67.3×7.3mm and weighs 148 grams. The iPhone SE (2020) is said to last about as long as the iPhone 8, with up to 13 hours of video playback time, and 40 hours of audio playback time.</p>
                    </div>
                </div>
                <div class="blog3 row">
                    <div class="col-12 py-4">
                        <p class="font-rale font-size-20 text-dark font-weight-bold">Redmi K30 5G Speed Edition launched with Snapdragon 768G SoC</p>
                        <img src="./assets/blog/Redmi-Speed.png" alt="blog3">
                    </div>
                    <div class="col-12 py-2">
                        <p class="font-baloo font-size-16">Xiaomi has today launched a new model under its Redmi K30 series. Redmi K30 5G Racing Edition aka Redmi K30 5G Extreme Edition aka Redmi K30 5G Speed Edition has been launched in China as a new addition to the Redmi K30 series of smartphones. The phone is powered by the new Snapdragon 768G SoC, making it the first phone to come with this processor. The Redmi K30 5G Racing Edition boasts of impressive specifications including a quad rear camera setup, dual selfie cameras, and 5G support, granted by the new processor. The phone comes in four color options i.e White, Blue Red, Purple and new Mint and single RAM and storage configuration.</p>
                        <p class="font-baloo font-size-16">The Redmi K30 5G Racing Edition is listed on JD.com for CNY 1,999 (approx Rs 21300) for the single 6GB RAM and 128GB storage option. The phone is now up for reservations till May 14, and it will go on flash sale at 10am on the same day. For now, details of other variants are not available. As of now, the Redmi K30 5G Racing edition will go on sale in China with no information on availability in international markets.</p>
                        <p class="font-baloo font-size-16">The dual-SIM (Nano) Redmi K30 5G Racing Edition features a 6.67-inch with 20:9 aspect ratio and a 120Hz refresh rate. It is powered by the Qualcomm Snapdragon 768G SoC which comes with the upgraded Adreno 620 GPU. The phone has 6GB of RAM.</p>
                        <p class="font-baloo font-size-16">In terms of camera the Redmi K30 Speed Edition is equipped with quad-camera setup with a combination of 64-megapixel primary Sony IMX686 lens with f/1.89 aperture, an 8-megapixel ultra-wide-angle lens with a 120-degree field of view, f/2.2 aperture, 2-megapixel depth sensor and 5-megapixel macro lens with f/2.4 aperture. For the front, the phone comes with a dual-selfie camera with a 20-megapixel primary lens and 2-megapixel depth sensor.</p>
                        <p class="font-baloo font-size-16">The Redmi K30 5G Racing Edition comes with 128GB of onboard storage. For connectivity, it has 5G, Wi-Fi, 4G-LTE, Bluetooth, NFC, a 3.5mm headphone jack, and a USB Type-C port for charging. There is also a side mounted fingerprint scanner. The Redmi K30 5G Racing Edition packs a 4,500mAh battery with support for 30W fast charging. The phone measures 165.3×76.6×8.79mm and weighs 208 grams.</p>
                    </div>
                </div>
                <div class="blog4 row">
                    <div class="col-12 py-4">
                        <p class="font-rale font-size-20 text-dark font-weight-bold">Oppo A31 (2020) With 6GB RAM & 128GB Storage Goes on Sale in India</p>
                        <img src="./assets/blog/Oppo-A31.png" alt="blog4">
                    </div>
                    <div class="col-12 py-2">
                        <p class="font-baloo font-size-16">Oppo A31 (2020) was launched in India on February 27 and the phone’s 4GB RAM variant went on sale two days later. Oppo was also supposed to launch the 6GB RAM variant of the smartphone in the second week of March, however, that was postponed due to the nationwide lockdown placed by the central government due to corona-virus. As per our reports, the company has confirmed that the 6GB RAM + 128GB storage variant will be available to purchase in India for the first time since its launch.</p>
                        <p class="font-baloo font-size-16">The Oppo A31(2020) features a 6.5-inch HD+ (720×1,600 pixels) display. The phone is powered by the octa-core MediaTek Helio P35 SoC paired with up to 6GB RAM. The internal storage options max out at 128GB and the storage is further expandable via a microSD card up to 256GB. The Device has dual-SIM (Nano) and runs Android 9 Pie with ColorOS 6.1.2 on top</p>
                        <p class="font-baloo font-size-16">Talking about the camera, the Oppo A31 (2020) packs a triple rear camera setup that includes a 12-megapixel primary camera. There are two more 2-megapixel cameras added to the rear camera module. For selfies and video calling, there’s an 8-megapixel camera housed in the waterdrop notch.</p>
                    </div>
                </div>
                <div class="blog5 row">
                    <div class="col-12 py-4">
                        <p class="font-rale font-size-20 text-dark font-weight-bold">iQoo 3: Enjoy high-end features and performance at reasonable prices</p>
                        <img src="./assets/blog/IQOO3.png" alt="blog5">
                    </div>
                    <div class="col-12 py-2">
                        <p class="font-baloo font-size-16">iQoo- the sub brand of Vivo in China has recently forayed into the Indian market with a mid-range phone model iQoo 3 with sophisticated features and 5G connectivity for its top model. The price starts from Rs. 36,990 and offers a really good value for the money thanks to the advanced hardware and refined features.</p>
                        <p class="font-baloo font-size-16">The model sports upmarket looks and has solid built quality. It has a 6.44” AMOLED display and the body is outlined with thin bezels. The hole-punch of the selfie camera is comfortably small. The phone is surrounded by a metal frame that adds to the visual elegance. You can feel some weight while holding the phone which indicates the solid built quality and reaffirms the premium equation. You will find the power and volume buttons on the right side in an accessible position. The former can easily be felt by your finger due to its eloquent texture which makes it a good companion for all your bedside phone usage during the night.</p>
                        <p class="font-baloo font-size-16">You will find the same subtle approach in its earpiece as well which is so tiny that it can hardly be noticed. On the right, you would find the power and volume buttons that are comfortably positioned for quick access. The former can easily be felt by your fingers due to its texture that makes it a bit more user-friendly. The model also f of a wisely positioned shoulder buttons that cushions the fingers when it is held horizontally. Google’s assistant can be beckoned with a smart button on the left. On the top, there is a 3.5mm Jack and at the bottom rests the loudspeaker and USB Type-C port. The phone is available in 3 different colors: Quantum Silver, Volcano Orange, and Tornado Black. Corning Gorilla Glass 6 perfectly provides excellent protection to the phone.</p>
                        <p class="font-baloo font-size-16">The quad-camera module at the model’s back houses a 48MP primary camera along with a secondary camera of 13MP offering interesting zoom capabilities (2X optical zoom and 20X digital zoom). It has a 2MP depth sensor and a 13mp wide-angle camera. The camera app does a fairly good job. The phone has wisely employed AI for automating some of the core photography tasks. You would love the output when shot during daylight. The zoom feature visually distorts with the quality though especially spoiling the edges and to some extent the color tones. The phone offers nice close-up shots and does full justice to both the subject and background giving it an elegant and balanced appeal. Just switch to the wide-angle camera to create some of the awesome macro shots with fine details.</p>
                        <p class="font-baloo font-size-16">The phone excels at detecting edges that offers a more refined look to the portrait shots as well. It also allows you to determine the blur level before snapping but lacks the fine details. The output in the low light doesn’t go beyond the average quality even with the night mode on. The lack of fine details puts you off and fails to satisfy our creative expectations. The selfie offers perfect output even in the bright conditions thanks to the automatically enabled HDR and applied beatification which is a default feature. The Video quality isn’t really good but manages to offer a manageable output. Daylight conditions affect the quality and the super steady mode doesn’t offer reliable steadiness to the output.</p>
                        <p class="font-baloo font-size-16">The 4,400 mAh battery affords it a comfortable battery life while the Super flash charge charger of 55W assures quick charging even when the phone is fully drained out. A sufficiently charged phone offers a battery life of around 20 hours even during pretty heavy usage like continuous video streaming. With modest use, you can further increase the life up to 36 hours (approx.). A fully drained out phone can be charged in around 1 hour. You would also find a small connector for the charger interestingly shaped as a pill that makes it practically easier to charge the phone even during an ongoing gaming session.</p>
                   </div>
                </div>
                <div class="blog6 row">
                    <div class="col-12 py-4">
                        <p class="font-rale font-size-20 text-dark font-weight-bold">OPPO Find X2 Series Launching in India Soon</p>
                        <img src="./assets/blog/Oppo-FindX2-1024x532.png" alt="blog6">
                    </div>
                    <div class="col-12 py-2">
                        <p class="font-baloo font-size-16">OPPO Find X2 series is set to launch in India soon, the company confirmed on Wednesday. OPPO posted on Twitter that the OPPO Find X2 is “coming to let you witness the #PerfectScreenOf2020 with a Billion colors and ultimate smoothness with its 120Hz Ultra Vision Screen!” The company is yet to announce the launch date, but we expect it to happen soon now. The Find X2 series was globally launched in March and will look to take on the Xiaomi Mi 10, OnePlus 8 series and Realme X50 Pro flagship phones in India. The OPPO flagship series will be sold on Amazon and the e-commerce site has a dedicated page now with the ‘Notify Me’ option for interested customers.</p>
                        <p class="font-baloo font-size-16">The series includes 2 models, OPPO Find X2 and Find X2 Pro, both of which offer identical designs and specifications and only vary in storage and cameras. Oppo Find X2 and Find X2 Pro feature 6.7-inch Quad HD+ OLED 2.5D curved glass display with 3168 x 1440 pixels resolution, HDR10+, 120Hz refresh rate, 800 nits brightness, 1200 nits peak brightness, 100% DCI-P3 Color Gamut. They feature Gorilla Glass 6 protection on the front and back. The phones are powered by the Snapdragon 865 chipset and will come with 5G support in India. While the Find X2 Pro comes with 12GB LPDDR5 RAM and 512GB internal storage, the vanilla model comes with 12GB LPDDR5 RAM and 256GB internal storage.</p>
                        <p class="font-baloo font-size-16">The Find X2 gets a triple camera setup that comprises of a 48MP Sony IMX689 primary sensor, 48MP ultra wide-angle lens, and a 32MP telephoto camera with support for 10x hybrid zoom and up to 60x digital zoom. Up front, the phones get a 32MP selfie camera. The regular Find X2 gets a slightly different camera setup with a 48MP Sony IMX586 main sensor, a 12MP wide-angle lens and 13MP telephoto lens with up to 20x digital zoom support.</p>
                        <p class="font-baloo font-size-16">The Find X2 Pro packs a 4,260mAh battery and is the first phone from the company to support 65W SuperVOOC 2.0 flash charging. The regular Find X2 gets a little smaller 4,200mAh battery but it does supports 65W SuperVOOC fast charging.</p>
                   </div>
                </div>
            </div>
        </section>
        <!-- !All Blogs -->